# Generated by Django 5.0.4 on 2025-01-05 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Estudio', 'Estudio'), ('Lectura', 'Lectura'), ('Descanso', 'Descanso')], max_length=20)),
                ('meta_diaria', models.FloatField(help_text='Meta diaria en horas')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('frecuencia', models.CharField(choices=[('Diaria', 'Diaria'), ('Semanal', 'Semanal')], max_length=20)),
                ('habito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion', to='Seguimiento.habito')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_completada', models.FloatField(help_text='Cantidad completada en horas')),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='Seguimiento.habito')),
            ],
        ),
    ]
